<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Codespirals.Base.Shared" Version="1.1.1.26110" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.10" />
  </ItemGroup>

</Project>
